# Imagem base oficial do Node 22.14
FROM node:22.14-alpine

# Diretório de trabalho dentro do container
WORKDIR /app

# Copia apenas os arquivos de dependência primeiro (melhora cache)
COPY package*.json ./

# Instala dependências
RUN npm install --legacy-peer-deps

# Copia o restante do projeto
COPY . .

# Compila o TypeScript
RUN npm run build

# Expondo a porta da aplicação
EXPOSE 3080

# Comando para iniciar a aplicação já compilada
CMD ["node", "dist/index.js"]
